version: "3"

services:
  postgres:
    container_name: postgres-db
    image: postgres:9.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8
      - VIRTUAL_HOST=postgres
      - VIRTUAL_PORT=5432

  web:
    container_name: Heart-Surgery
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=35.175.196.123, drbakhshaliyev.com, www.drbakhshaliyev.com
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - "postgres"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/example.com:/etc/nginx/sites-available/heart_project
      - /etc/nginx/sites-enabled/
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - nginx-proxy
